
scale_value: 1
scale_value: 1
self.camera[current_idx].scale: 1
prev_scale: 1
scale_value: 1
self.camera[current_idx].scale: 1
prev_scale: 1
scale_value: 1
self.camera[current_idx].scale: 1
prev_scale: 1
scale_value: 1
self.camera[current_idx].scale: 1
prev_scale: 1
scale_value: 1
self.camera[current_idx].scale: 1
prev_scale: 1
scale_value: 1
self.camera[current_idx].scale: 1
prev_scale: 1
scale_value: 1
self.camera[current_idx].scale: 1
prev_scale: 1
scale_value: 1
self.camera[current_idx].scale: 1
prev_scale: 1
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/lsr/anaconda3/envs/MonoGS/lib/python3.7/site-packages/wandb/sdk/lib/exit_hooks.py", line 41, in exc_handler
    def exc_handler(
KeyboardInterrupt
Original exception was:
Traceback (most recent call last):
  File "slam.py", line 251, in <module>
    slam = SLAM(config, save_dir=save_dir)
  File "slam.py", line 109, in __init__
    self.frontend.run()
  File "/home/lsr/MonoGS_Version_Control/MonoGS/utils/slam_frontend.py", line 606, in run
    self.sync_backend(data)
  File "/home/lsr/MonoGS_Version_Control/MonoGS/utils/slam_frontend.py", line 416, in sync_backend
    self.cameras[kf_id].update_RT(kf_R.clone(), kf_T.clone())
  File "/home/lsr/MonoGS_Version_Control/MonoGS/utils/camera_utils.py", line 112, in update_RT
    self.R = R.to(device=self.device)
  File "/home/lsr/anaconda3/envs/MonoGS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1240, in __setattr__
    elif modules is not None and name in modules:
KeyboardInterrupt